export const mockData = [
  {
    id: "101",
    name: "Gourmet Bistro",
    rating: 4.5,
    address: "Cyber Hub, Gurugram",
    imageURL: "/img1.jpg",
  },
  {
    id: "102",
    name: "Tandoori Tadka",
    rating: 4.8,
    address: "Sector 29, Gurugram",
    imageURL: "/img2.jpg",
  },
  {
    id: "103",
    name: "[translate:Swad Ka Safar]",
    rating: 4.6,
    address: "Golf Course Road, Gurugram",
    imageURL: "/img3.jpg",
  },
  {
    id: "104",
    name: "Biryani Buzz",
    rating: 4.7,
    address: "Sohna Road, Gurugram",
    imageURL: "/img4.jpg",
  },
  {
    id: "105",
    name: "Masala Magic",
    rating: 4.5,
    address: "MG Road, Gurugram",
    imageURL: "/img6.jpg",
  },
  {
    id: "106",
    name: "Rasoi Royale",
    rating: 4.9,
    address: "MG Road, Gurugram",
    imageURL: "/img7.jpg",
  },
  {
    id: "107",
    name: "Epicurean Haven",
    rating: 4.6,
    address: "Sector 31, Gurugram",
    imageURL: "/img8.jpg",
  },
  {
    id: "108",
    name: "Nukkad Ki Rasoi",
    rating: 4.4,
    address: "Sector 56, Gurugram",
    imageURL: "/img9.jpg",
  },
  {
    id: "109",
    name: "Taj Mahal Treats",
    rating: 5.0,
    address: "Old Delhi Road, Gurugram",
    imageURL: "/img10.jpg",
  },
  {
    id: "110",
    name: "Rasoi Ka Rang",
    rating: 4.3,
    address: "Patience Market, Gurugram",
    imageURL: "/img11.jpg",
  },
  {
    id: "111",
    name: "Spice Table",
    rating: 4.4,
    address: "Udyog Vihar, Gurugram",
    imageURL: "/img12.jpg",
  },
  {
    id: "112",
    name: "Desi Dhamaal",
    rating: 4.2,
    address: "Sector 44, Gurugram",
    imageURL: "/img13.jpg",
  },
  {
    id: "113",
    name: "Ambrosial Bhavan",
    rating: 4.8,
    address: "Sector 45, Gurugram",
    imageURL: "/img14.jpg",
  },
  {
    id: "114",
    name: "Heritage Haven",
    rating: 4.6,
    address: "DLF Phase 1, Gurugram",
    imageURL: "/img14.jpg",
  },
  {
    id: "115",
    name: "Mughal Majestic",
    rating: 4.7,
    address: "Civil Lines, Gurugram",
    imageURL: "/img15.jpg",
  },
];
